import type { Listing } from "@/src/lib/models";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "raw-001",
    supplier_id: "seller-demo-001",
    supplier_name: "Centro de Servicio Demo",
    grade: "409",
    finish: "2B",
    thickness_mm: 1.2,
    width_mm: 300,
    price_per_mt: 1650,
    available_mt: 8.5,
    location: "San Luis Potosí",
    inventory_status: "active",
  },
  {
    id: "raw-002",
    supplier_id: "seller-demo-001",
    supplier_name: "Centro de Servicio Demo",
    grade: "430",
    finish: "BA",
    thickness_mm: 0.8,
    width_mm: 250,
    price_per_mt: 1820,
    available_mt: 6.2,
    location: "Querétaro",
    inventory_status: "active",
  },
  {
    id: "raw-003",
    supplier_id: "seller-demo-002",
    supplier_name: "Proveedor Verificado",
    grade: "304",
    finish: "2B",
    thickness_mm: 1.0,
    width_mm: 400,
    price_per_mt: 2450,
    available_mt: 10.0,
    location: "Monterrey",
    inventory_status: "active",
  },
];
